### ISSUE TITLE
defaultの設定を記載する

### ISSUE THREAD

**Issue by YusuiHoshino** [AizuGeekDojo/LaserCutterInstruction#24]
by wancom

**Comment by wancom** [comment]
Speedy100
- サイズ設定
  - User-defined Size
  - 幅 610mm
  - 高さ 305mm
  - ジョブサイズに最小化

Speedy300
- サイズ設定
  - User-defined Size
  - 幅 726mm
  - 高さ 432mm
  - ジョブサイズに最小化

共通
- 加工オプション
  - 加工モード: レリーフ
  - カットライン: 無し
  - 解像度: お好みで

**Comment by YusuiHoshino** [comment]
#25で解決済み
